services:
  - type: web
    runtime: static
    name: beyond-the-chatbot
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
