import { useEffect, useMemo, useRef, useState } from 'react'
import { useApp } from '../context/AppContext.jsx'
import { MODAL_BULLETS } from '../data/modalBullets.js'

/*
  Narration: real audio generated by scripts/generate-narration.mjs lives at
  public/audio/<key>.mp3 (key = the modal's fig.file minus ".png"). The modal
  plays that file; if it's missing or fails to load, it falls back to the
  original SIMULATED progress bar so the UI contract (auto-play when narration
  mode is on, manual ▶ otherwise) always holds.
*/
// Each modal has up to PLATE_VARIANTS generated plates in public/plates/<key>/.
// We pick one at random every time the modal opens, so the deck looks a little
// different on each run. The CSS gradient on .img stays as the load fallback.
const PLATE_VARIANTS = 4

export default function Modal() {
  const { activeModal, closeModal, narrationMode, selfGuided } = useApp()
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [variant, setVariant] = useState(1)
  const [audioBroken, setAudioBroken] = useState(false)
  const [timing, setTiming] = useState(null)   // { paragraphs: [[{w,s,e}]] } for word highlighting
  const [activeWord, setActiveWord] = useState(-1) // flat index of the word being spoken
  const timer = useRef(null)
  const audioRef = useRef(null)
  const rafRef = useRef(0)
  const activeRef = useRef(-1)

  const color = activeModal?.color || 'var(--accent)'
  // narration/bullets key: explicit audioKey, else the plate image basename
  const base = activeModal?.audioKey || (activeModal?.fig ? activeModal.fig.file.replace(/\.png$/i, '') : null)
  const audioSrc = base ? `${import.meta.env.BASE_URL}audio/${base}.mp3` : null

  // flat, time-sorted list of words for fast lookup, + per-paragraph index offsets
  const { flatWords, paraOffsets } = useMemo(() => {
    const flat = [], offsets = []
    let n = 0
    for (const para of timing?.paragraphs || []) {
      offsets.push(n)
      for (const word of para) { flat.push(word); n++ }
    }
    return { flatWords: flat, paraOffsets: offsets }
  }, [timing])

  const clearSim = () => { clearInterval(timer.current); timer.current = null }

  // simulated fallback (no audio file available)
  const simulate = () => {
    clearSim()
    setPlaying(true)
    setProgress(p => (p >= 100 ? 0 : p))
    timer.current = setInterval(() => {
      setProgress(p => {
        if (p >= 100) { clearSim(); setPlaying(false); return 100 }
        return p + 0.7
      })
    }, 40)
  }

  const play = () => {
    const a = audioRef.current
    if (a && audioSrc && !audioBroken) {
      clearSim()
      if (progress >= 100) { a.currentTime = 0; setProgress(0) }
      a.play().then(() => setPlaying(true)).catch(() => { setAudioBroken(true); simulate() })
    } else {
      simulate()
    }
  }

  const stop = () => {
    const a = audioRef.current
    if (a && !a.paused) a.pause()
    clearSim()
    setPlaying(false)
  }

  // on every (re)open: reset, re-roll the plate, load word timings, auto-play if on
  useEffect(() => {
    clearSim()
    setPlaying(false); setProgress(0); setAudioBroken(false)
    setActiveWord(-1); activeRef.current = -1
    const a = audioRef.current
    if (a) { try { a.pause(); a.currentTime = 0 } catch {} }
    if (activeModal?.fig) setVariant(1 + Math.floor(Math.random() * PLATE_VARIANTS))

    let cancelled = false
    setTiming(null)
    if (base) {
      fetch(`${import.meta.env.BASE_URL}audio/${base}.json`)
        .then(r => (r.ok ? r.json() : null))
        .then(j => { if (!cancelled) setTiming(j && j.paragraphs ? j : null) })
        .catch(() => {})
    }

    let autoId
    if (activeModal && selfGuided && narrationMode) autoId = setTimeout(play, 80)
    return () => { cancelled = true; clearTimeout(autoId) }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeModal])

  // karaoke loop: while real audio plays, highlight the word under the playhead
  useEffect(() => {
    if (!playing || audioBroken || !flatWords.length) return
    const tick = () => {
      const a = audioRef.current
      if (a) {
        const t = a.currentTime
        // rightmost word whose start time is <= t
        let lo = 0, hi = flatWords.length - 1, idx = -1
        while (lo <= hi) {
          const mid = (lo + hi) >> 1
          if (flatWords[mid].s <= t) { idx = mid; lo = mid + 1 } else { hi = mid - 1 }
        }
        if (idx !== activeRef.current) { activeRef.current = idx; setActiveWord(idx) }
      }
      rafRef.current = requestAnimationFrame(tick)
    }
    rafRef.current = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(rafRef.current)
  }, [playing, audioBroken, flatWords])

  useEffect(() => () => { clearSim(); cancelAnimationFrame(rafRef.current) }, [])

  if (!activeModal) return null
  const { name, tag, plno, body = [], fig } = activeModal
  const bullets = base ? MODAL_BULLETS[base] : null
  // Self-Guided OFF = presenter mode: terse bullets, no narration controls.
  const presenter = !selfGuided

  return (
    <div className="overlay" onClick={(e) => { if (e.target === e.currentTarget) closeModal() }}>
      <div className="modal">
        {audioSrc && (
          <audio
            ref={audioRef}
            src={audioSrc}
            preload="auto"
            onTimeUpdate={(e) => { const a = e.currentTarget; if (a.duration) setProgress((a.currentTime / a.duration) * 100) }}
            onEnded={() => { setPlaying(false); setProgress(100) }}
            onError={() => setAudioBroken(true)}
          />
        )}
        <div className="modal-tools">
          {!presenter && (
            <button
              className="iconbtn play"
              style={{ color, borderColor: color }}
              onClick={(e) => { e.stopPropagation(); playing ? stop() : play() }}
              title={playing ? 'Pause narration' : 'Play narration'}
            >
              {playing ? '❚❚' : '▶'}
            </button>
          )}
          <button className="iconbtn" onClick={closeModal} title="Close (Esc)">✕</button>
        </div>

        <div className="modal-inner">
          {plno && (
            <div className="plno">
              <span className="sw" style={{ background: color }} />
              <span>{plno}</span>
            </div>
          )}
          <h2>{name}</h2>
          {tag && <div className="tag" style={{ color }}>{tag}</div>}

          {fig && (
            <div className="figplate">
              <div
                className="img"
                style={{
                  '--fig': color,
                  backgroundImage: `url("${import.meta.env.BASE_URL}plates/${fig.file.replace(/\.png$/i, '')}/${String(variant).padStart(2, '0')}.png")`,
                  backgroundSize: 'cover',
                  backgroundPosition: 'center',
                }}
              />
              <div className="cap">
                <span><b>Fig. {fig.n}</b> — {fig.file}</span>
                <span>Plate · 1152×768</span>
              </div>
            </div>
          )}

          <div className="rule" />
          {presenter && bullets ? (
            <ul className="modal-bullets">
              {bullets.map((b, i) => (
                <li key={i}><span className="bmk" style={{ color }}>—</span>{b}</li>
              ))}
            </ul>
          ) : timing ? (
            timing.paragraphs.map((para, pi) => (
              <p key={pi} className={pi === timing.paragraphs.length - 1 ? 'last' : ''}>
                {para.map((word, wi) => {
                  const idx = paraOffsets[pi] + wi
                  const on = idx === activeWord
                  return (
                    <span key={wi}>
                      <span className={on ? 'spoken on' : 'spoken'} style={on ? { color } : undefined}>{word.w}</span>
                      {wi < para.length - 1 ? ' ' : ''}
                    </span>
                  )
                })}
              </p>
            ))
          ) : (
            body.map((p, i) => (
              <p key={i} className={i === body.length - 1 ? 'last' : ''}>{p}</p>
            ))
          )}

          {!presenter && (playing || progress > 0) && (
            <div className="narr">
              <span className="lab">{narrationMode ? 'Auto-narrating' : 'Narrating'}</span>
              <div className="track"><i style={{ width: progress + '%', background: color }} /></div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
